Repository TEAM-SAMSION/Backend, pull requests merged in 2023-11, with the labels that each got.

#99 Pet 157 refactor : RegisterQueryService 조회 메소드들에서 Function 기반에서 Supplier 기반으로 수정
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
Labels: 🔨 Refactor

#101 Pet 156 feat : 사용자 탈퇴 및 페밀리 탈퇴 시 검증 로직 추가
  Api-Module/src/docs/asciidoc/Error.adoc
  Api-Module/src/docs/asciidoc/Index.adoc
  Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/UnregistrableException.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
Labels: ✨ Feature

#102 Pet 158 chore : jaCoCo 설정 추가
  Common-Module/src/test/java/com/petmory/commonmodule/.gitkeep
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/dto/OAuthRequest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/GoogleOAuthHandlerTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/KakaoOAuthHandlerTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/NaverOAuthHandlerTest.java
  Domain-Module/Auth-Module/Auth-Presentation/src/test/java/com/pawith/authpresentation/OAuthControllerTest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/AuthorityChangeRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/ScheduledDateChangeRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/TodoDescriptionChangeRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/.gitkeep
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoChangeUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoRateGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoTeamGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
  build.gradle
  gradle/jacoco.gradle
  gradle/test.gradle
Labels: ✅ Test, ⚙ Setting

#104 Pet-161 refactor : 소셜 로그인시 사용자 기본 프로필 설정 추가
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/UserMapper.java
Labels: 🔨 Refactor

#105 refactor : 카테고리 하위 투두 조회 순서 섞이는 문제 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
Labels: 🔨 Refactor

#106 Pet 145 feat : 패밀리 생성시 한줄 소개 및 팻(과, 종) 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/PetRegisterRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/TodoTeamCreateRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/PetMapper.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Pet.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoTeam.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/vo/PetSpecies.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: ✨ Feature

#107 Pet 164 refactor : ListResponse 추가, Todo 리스트 조회 수정
  Common-Module/src/main/java/com/pawith/commonmodule/response/ListResponse.java
  Common-Module/src/main/java/com/pawith/commonmodule/response/SliceResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryInfoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterInfoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoTeamGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Assign.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: ✅ Test, 🔨 Refactor

#108 Pet 163 feat : 관리자 페이지 권한 수정에서의 검증 추가
  Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/ChangeRegisterUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/UnchangeableException.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#110 Pet 154 chore : 환경 변수 참조 기반 application.yml으로 변경
  .deploy/docker-compose.yml
  .github/workflows/CD.yml
  Api-Module/src/main/resources/.gitkeep
  Api-Module/src/main/resources/application-auth.yml
  Api-Module/src/main/resources/application-aws.yml
  Api-Module/src/main/resources/application-db.yml
  Api-Module/src/main/resources/application.yml
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/entity/Token.java
Labels: 🌏 Deploy&Infra, ⚙ Setting

#109 PET-163 refactor : 관리자 페이지 권한 수정 시 Enum 활용
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/AuthorityChangeRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/ChangeRegisterUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
Labels: 🔨 Refactor

#111 PET-165 fix : Assign 조회 수정
  Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/AssignNotFoundException.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
Labels: 🐞 BugFix

#112 Pet 166 feat : 카테고리 조회 API (관리자 페이지에서 사용) 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryManageInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
Labels: ✨ Feature, ✅ Test

#113 Pet 167 feat : Todo 삭제 API 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoDeleteOnTodoHandler.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/event/TodoDeleteEvent.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoDeleteUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignDeleteService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoDeleteService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Labels: ✨ Feature, ✅ Test

#114 Pet 144 feat : 알림 조회 및 여부 조회, fcm device token 저장 API 추가
  Alarm-Module/build.gradle
  Alarm-Module/src/docs/Alarm-API.adoc
  Alarm-Module/src/main/java/com/pawith/alarmmodule/controller/AlarmController.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/controller/AlarmUserController.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/Alarm.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/AlarmCategory.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/AlarmUser.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/DeviceType.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/repository/AlarmRepository.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/repository/AlarmUserRepository.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/AlarmService.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/AlarmUserService.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/dto/request/DeviceTokenSaveRequest.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/dto/response/AlarmExistenceResponse.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/dto/response/AlarmInfoResponse.java
  Alarm-Module/src/test/java/com/pawith/alarmmodule/controller/AlarmControllerTest.java
  Alarm-Module/src/test/java/com/pawith/alarmmodule/controller/AlarmUserControllerTest.java
  Api-Module/src/docs/asciidoc/Index.adoc
  build.gradle
  gradle/jacoco.gradle
  gradle/restdocs.gradle
  settings.gradle
Labels: ✨ Feature

#115 Pet 168 feat : TodoTeam 가입한 사용자 검색 API 추가, 사용자 조회 API 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterSearchInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/UserRepository.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#116 Pet 144 feat : todo 알림 설정 API 추가
  Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoNotificationCreateUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoNotification.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationSaveService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Labels: ✨ Feature

#118 Pet 171 refactor : Error 클래스 인터페이스로 수정 후 각 도메인에서 Error 인터페이스 구현체 사용하도록 수정
  Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
  Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/OAuthInvoker.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/AppleOAuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/KakaoOAuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/utils/TokenExtractUtils.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/exception/AuthError.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/jwt/JWTProvider.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenQueryServiceImpl.java
  Domain-Module/Auth-Module/Auth-Domain/src/test/java/com/pawith/authdomain/jwt/JWTProviderTest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/exception/TodoException.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoChangeUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/TodoError.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/exception/WrongScheduledDateException.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterSaveService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
  Domain-Module/User-Module/User-Application/src/test/java/com/pawith/userapplication/handler/UserSignUpHandlerTest.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/exception/UserError.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserAuthorityQueryService.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java
  Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/userdomain/service/UserQueryServiceTest.java
  Image-Module/src/main/java/com/pawith/imagemodule/exception/FileError.java
  Image-Module/src/main/java/com/pawith/imagemodule/infrastructure/s3/S3ImageDeleteServiceImpl.java
  Image-Module/src/main/java/com/pawith/imagemodule/infrastructure/s3/S3ImageUploadService.java
  gradle/test.gradle
Labels: 🔨 Refactor

#119 Pet 144 feat : Todo 알림 생성 로직 추가
  Alarm-Module/src/main/java/com/pawith/alarmmodule/config/FireBaseConfig.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/config/SchedulingConfig.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/Alarm.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/AlarmUser.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/DeviceType.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/vo/AlarmBody.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/exception/AlarmError.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/exception/AlarmException.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/exception/FcmException.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/AlarmSendService.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/AlarmService.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/AlarmUserService.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/dto/request/DeviceTokenSaveRequest.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/dto/response/AlarmInfoResponse.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/service/impl/FcmSendService.java
  Alarm-Module/src/test/java/com/pawith/alarmmodule/controller/AlarmControllerTest.java
  Alarm-Module/src/test/java/com/pawith/alarmmodule/controller/AlarmUserControllerTest.java
  Api-Module/build.gradle
  Common-Module/src/main/java/com/pawith/commonmodule/config/RetryableConfig.java
  Common-Module/src/main/java/com/pawith/commonmodule/enums/AlarmCategory.java
  Common-Module/src/main/java/com/pawith/commonmodule/event/NotificationEvent.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoNotification.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/dao/NotificationDao.java
  build.gradle
  gradle/fcm.gradle
  gradle/spring.gradle
Labels: ✨ Feature

#120 PET-173 chore : firebase.json 설정 추가
  .github/workflows/CD.yml
Labels: 🐞 BugFix

#125 PET-175 docs : 모듈 의존성 UML 교체
  .github/docs/Dependency.png
  .github/docs/components-Modules.png
  README.md
Labels: 📃 Docs

#127 Pet 176 refactor : 자바 11 -> 17로 변경 및 SpringBoot 버전 3으로 변경
  .deploy/Dockerfile
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  Alarm-Module/src/docs/Alarm-API.adoc
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/Alarm.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/AlarmUser.java
  Alarm-Module/src/main/java/com/pawith/alarmmodule/entity/vo/AlarmBody.java
  Alarm-Module/src/test/java/com/pawith/alarmmodule/controller/AlarmControllerTest.java
  Common-Module/src/main/java/com/pawith/commonmodule/domain/BaseEntity.java
  Common-Module/src/main/java/com/pawith/commonmodule/response/ListResponse.java
  Common-Module/src/main/java/com/pawith/commonmodule/util/DomainFieldUtils.java
  Domain-Module/Auth-Module/Auth-Application/build.gradle
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/entity/Token.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/jwt/JWTProperties.java
  Domain-Module/Auth-Module/Auth-Presentation/src/docs/asciidoc/Auth-API.adoc
  Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/common/security/SecurityConfig.java
  Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/common/security/filter/JWTAuthenticationFilter.java
  Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/common/security/filter/JWTEntryPoint.java
  Domain-Module/Auth-Module/Auth-Presentation/src/test/java/com/pawith/authpresentation/OAuthControllerTest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/AssignChangeUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Assign.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Category.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Pet.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoNotification.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoTeam.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/vo/PetSpecies.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/PetQueryService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/PetControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/PathHistory.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/UserAuthority.java
  README.md
  build.gradle
  gradle/spring.gradle
Labels: 🔨 Refactor

#128 PET-177 refactor : 엔티티 필드 수정 메서드 null 처리 추가
  Common-Module/src/main/java/com/pawith/commonmodule/util/DomainFieldUtils.java
Labels: 🔨 Refactor

#130 Pet 177 feat : 탈퇴 관련 API와 예외처리 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/dto/request/WithdrawReasonCreateRequest.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/dto/response/UserJoinTermResponse.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/WithdrawMapper.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/service/UserInfoGetUseCase.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/service/WithdrawReasonCreateUseCase.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/WithdrawReason.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/UserRepository.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/WithdrawReasonRepository.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/WithDrawSaveService.java
  Domain-Module/User-Module/User-Presentation/src/docs/asciidoc/User-API.adoc
  Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserController.java
  Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserControllerTest.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#131 PET-177 refactor : 펫 생성,조회,수정 DTO 필드 이름 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/PetRegisterRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/PetInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/PetMapper.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/PetControllerTest.java
Labels: 🔨 Refactor

#133 Pet 182 refactor : 카테고리 하위 투두 조회 로직 수정, 펫 정보 업데이트 로직 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Pet.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Labels: 🔨 Refactor

#134 Pet 186 refactor : 카테고리 하위 todo 조회 최적화 및 알림 여부 필드 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoNotificationInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoMapper.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoWithdrawGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationQueryService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Labels: ✨ Feature, 🔨 Refactor

#135 Pet 190 fix : todo 알림 시간 설정이 되어있으면 기존 시간 변경하는 방식으로 로직 수정
  Common-Module/src/main/java/com/pawith/commonmodule/util/DomainFieldUtils.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoNotificationCreateUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/TodoNotification.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoNotificationSaveService.java
Labels: 🐞 BugFix

#136 PET-189 refactor : 쿼리 수정, 탈퇴 검증 로직 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/UserRepository.java
Labels: ✅ Test, 🔨 Refactor

#137 Pet-191 fix : 사용자 권한 저장 방식 수정
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/UserAuthority.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserAuthoritySaveService.java
  Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/userdomain/service/UserAuthoritySaveServiceTest.java
Labels: 🐞 BugFix

#138 Pet 189 feat : 가장 최근에 생성한 TodoTeam 조회 API 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: ✨ Feature, ✅ Test

#139 Pet 192 chore : dev - CI/CD, nginx-CD 플로우 수정
  .deploy/docker-compose-dev.yml
  .deploy/nginx/conf-dev/nginx.conf
  .deploy/promtail-dev.yaml
  .github/workflows/dev-CD.yml
  .github/workflows/dev-CI.yml
  .github/workflows/dev-Nginx-CD.yml
Labels: 🌏 Deploy&Infra

#140 Pet 192 chore : 배포 서버 CI,CD, nginx CD 추가
  .deploy/docker-compose-prod.yml
  .deploy/nginx/conf-prod/nginx.conf
  .deploy/promtail-prod.yaml
  .github/docs/components-Modules.png
  .github/workflows/CD-dev.yml
  .github/workflows/CD-prod.yml
  .github/workflows/CI-dev.yml
  .github/workflows/CI-prod.yml
  .github/workflows/Nginx-CD-dev.yml
  .github/workflows/Nginx-CD-prod.yml
  Api-Module/build.gradle
  Api-Module/src/main/java/com/pawith/apimodule/presentation/controller/TestController.java
Labels: 🌏 Deploy&Infra

#141 Pet 189 refactor : 쿼리 조건 추가, Todo 낙관적 락 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandler.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/handler/TodoCompletionCheckOnTodoHandlerTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
Labels: 🔨 Refactor

#142 Pet 194 refactor : 팀 코드로 팀 조회 API 응답값 수정, 서비스 탈퇴 검증 로직 API로 분리
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSearchInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: ✅ Test, 🔨 Refactor

#143 Pet 193 refactor : Register에 가입 날짜 칼럼 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
Labels: 🔨 Refactor

#144 PET-193 refactor : 가입한 날짜 LocalDateTime으로 변경
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
Labels: 🔨 Refactor

#145 PET-195 fix : todo 조회시 카테고리 활성화 반영
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
Labels: 🐞 BugFix

#146 PET-195 fix : Register 엔티티에 userId 인덱스 설정 수정
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
Labels: 🐞 BugFix

#147 PET-195 fix : 사용자 기본 프로필 이미지 변경
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
Labels: 🔨 Refactor

#148 PET-197 refactor : 소셜 로그인 access token 헤더 받도록 수정
  Domain-Module/Auth-Module/Auth-Presentation/src/docs/asciidoc/Auth-API.adoc
  Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/OAuthController.java
  Domain-Module/Auth-Module/Auth-Presentation/src/test/java/com/pawith/authpresentation/OAuthControllerTest.java
Labels: 🔨 Refactor

#149 PET-198 fix : User 엔티티 필드 수정시 메소드 DomainFieldUtils로 수정
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
Labels: 🐞 BugFix

#150 PET-198 fix : User 엔티티 필드 수정시 메소드 DomainFieldUtils build 수정
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
Labels: 🐞 BugFix

#152 Pet 201 refactor : 알림 쿼리 수정 및 알림 조회시 내림차순으로 하도록 수정
  Alarm-Module/src/main/java/com/pawith/alarmmodule/repository/AlarmRepository.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoNotificationRepository.java
Labels: 🔨 Refactor

#153 PET-202 fix : CD 수정
  .github/workflows/CD-prod.yml
  .github/workflows/Nginx-CD-prod.yml
Labels: 🐞 BugFix, 🌏 Deploy&Infra

#155 PET-202 refactor : logback 로그 용량 크기 조정
  Api-Module/src/main/resources/logback.xml
Labels: ⚙ Setting

#156 PET-200 refactor : 서비스 탈퇴 검증 수정
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterValidateService.java
Labels: 🔨 Refactor

#158 Pet 206 fix : 알림 설정 시간과 비교시 스케줄러 시작 시간과 비교하도록 수정
  .github/workflows/CD-prod.yml
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/TodoNotificationHandler.java
Labels: 🐞 BugFix

#160 Pet 207 refactor : 투두 화면 카테고리 조회 로직 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Category.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/CategoryQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
Labels: ✅ Test, 🔨 Refactor
