Repository TEAM-SAMSION/Backend, pull requests merged in 2023-08, with the labels that each got.

#11 pr 템플릿 생성
  pull_request_template.md
Labels: 📃 Docs

#12 pr 템플릿 위치 변경
  .github/pull_request_template.md
Labels: 📃 Docs

#14 PET-44 chore : actuator, prometheus 의존성 추가
  Api-Module/build.gradle
Labels: 🐞 BugFix, 🌏 Deploy&Infra, ⚙ Setting

#15 PET-46 로그 수집기 로직 수정
  Log-Module/log-aop/src/main/java/com/petmory/log/aop/LogTrace.java
  Log-Module/log-aop/src/main/java/com/petmory/log/aop/Pointcuts.java
Labels: 🔨 Refactor

#16 Pet 41 feat : JWT 인증 필터 추가 및 JWT 인증, 인증 타입 분리, 이메일 추출 서비스 추가
  Api-Module/src/main/java/com/petmory/apimodule/ApiModuleApplication.java
  Auth-Module/JWT/src/main/java/com/petmory/jwt/JWTProvider.java
  Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/JWTAuthenticationToken.java
  Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/SecurityConfig.java
  Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/SecurityHandler.java
  Auth-Module/auth-adaptor/src/main/java/com/petmory/authmodule/config/security/filter/JWTAuthenticationFilter.java
  Auth-Module/auth-application/build.gradle
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/config/OAuthConfig.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/consts/AuthConsts.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/consts/IgnoredPathConsts.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/exception/AuthException.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/common/exception/InvalidAuthorizationTypeException.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/port/in/JWTExtractEmailUseCase.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/port/in/JWTExtractTokenUseCase.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/port/in/JWTVerifyUseCase.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/service/JWTExtractEmailService.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/service/JWTExtractTokenService.java
  Auth-Module/auth-application/src/main/java/com/petmory/authmodule/application/service/JWTVerifyService.java
  Auth-Module/build.gradle
  Common-Module/src/main/java/com/petmory/commonmodule/exception/Error.java
Labels: ✨ Feature, 🔨 Refactor

#19 PET-69 feat : 소셜 로그인 결과 사용자 email 기반 AccessToken, RefreshToken 생성 로직 추가
  Auth-Module/JWT/src/main/java/com/pawith/jwt/JWTConsts.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/config/OAuthConfig.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/consts/AuthConsts.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/dto/OAuthResponse.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/factory/DefaultOAuthFactory.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/subject/OAuthSubject.java
Labels: ✨ Feature, 🔨 Refactor

#20 PET-68 feat : 애플 로그인 추가
  Auth-Module/auth-application/build.gradle
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/dto/Provider.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/observer/Impl/AppleOAuthObserver.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/observer/feign/AppleFeignClient.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/observer/feign/response/Keys.java
Labels: ✨ Feature

#23 Pet 71 feat: 이벤트 기반 user 생성
  Auth-Module/auth-application/build.gradle
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/observer/Impl/AppleOAuthObserver.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/subject/OAuthSubject.java
  Common-Module/src/main/java/com/pawith/commonmodule/annotation/DomainService.java
  Common-Module/src/main/java/com/pawith/commonmodule/annotation/Mapper.java
  Common-Module/src/main/java/com/pawith/commonmodule/domain/BaseEntity.java
  Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
  User-Module/build.gradle
  User-Module/user-application/build.gradle
  User-Module/user-application/src/main/java/com/pawith/usermodule/application/handler/UserSignUpHandler.java
  User-Module/user-application/src/main/java/com/pawith/usermodule/application/handler/event/UserSignUpEvent.java
  User-Module/user-application/src/main/java/com/pawith/usermodule/application/mapper/UserMapper.java
  User-Module/user-domain/build.gradle
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/entity/User.java
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/exception/AccountAlreadyExistException.java
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/exception/UserException.java
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/exception/UserNotFoundException.java
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/repository/UserRepository.java
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/service/UserQueryService.java
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/service/UserSaveService.java
  settings.gradle
Labels: ✨ Feature

#24 Pet 72 Fix : ApplicationEventPublisher 빈등록 및 JpaRepository 빈등록 문제 수정
  Api-Module/src/main/java/com/pawith/apimodule/ApiModuleApplication.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/observer/subject/OAuthSubject.java
  Common-Module/src/main/java/com/pawith/commonmodule/config/JpaConfig.java
  User-Module/user-application/src/main/java/com/pawith/usermodule/application/handler/UserSignUpHandler.java
  User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/entity/User.java
Labels: 🐞 BugFix, 🔨 Refactor

#26 PET-73 fix : deploy 패키지 이름 .deploy로 수정
  .github/workflows/CD.yml
Labels: 🐞 BugFix, 🌏 Deploy&Infra

#27 PET-74 feat : 네이버 소셜로그인 추가
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/config/OAuthConfig.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/command/OAuthInvoker.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/command/handler/impl/GoogleOAuthHandler.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/command/handler/impl/NaverOAuthHandler.java
Labels: ✨ Feature, 🔨 Refactor

#28 PET-75 feat : 카카오 소셜 로그인 추가
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/command/handler/impl/KakaoOAuthHandler.java
Labels: ✨ Feature

#29 Pet 77 test : JWTProvider 테스트 코드 추가
  Auth-Module/JWT/src/main/java/com/pawith/jwt/JWTProvider.java
  Auth-Module/JWT/src/test/java/com/pawith/jwt/JWTProviderTest.java
  Auth-Module/JWT/src/test/java/com/pawith/jwt/JWTTestConsts.java
  Common-Module/src/main/java/com/pawith/commonmodule/utill/ApplicationContextUtils.java
  build.gradle
Labels: ✅ Test

#30 Pet 78 test : user 테스트 코드 추가
  Domain-Module/User-Module/user-application/.jqwik-database
  Domain-Module/User-Module/user-application/src/main/java/com/pawith/usermodule/application/handler/UserSignUpHandler.java
  Domain-Module/User-Module/user-application/src/main/java/com/pawith/usermodule/application/handler/event/UserSignUpEvent.java
  Domain-Module/User-Module/user-application/src/test/java/com/pawith/user/application/handler/UserSignUpHandlerTest.java
  Domain-Module/User-Module/user-domain/.jqwik-database
  Domain-Module/User-Module/user-domain/src/main/java/com/pawith/usermodule/domain/service/UserQueryService.java
  Domain-Module/User-Module/user-domain/src/test/java/com/pawith/user/domain/UserQueryServiceTest.java
  Domain-Module/User-Module/user-domain/src/test/java/com/pawith/user/domain/UserSaveServiceTest.java
  settings.gradle
Labels: ✅ Test

#31 Pet 80 chore : RestDocs 설정추가
  Api-Module/src/main/resources/static/docs/Auth-API.html
  Auth-Module/auth-adaptor/src/docs/asciidoc/Auth-API.adoc
  Auth-Module/auth-adaptor/src/test/java/com/pawith/authmodule/adaptor/api/OAuthControllerTest.java
  Auth-Module/auth-adaptor/src/test/java/com/pawith/authmodule/adaptor/api/TestSpringBootApplicationConfig.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/consts/IgnoredPathConsts.java
  Auth-Module/build.gradle
  Common-Module/Test-Module/build.gradle
  Common-Module/Test-Module/src/main/java/com/pawith/testmodule/BaseRestDocsTest.java
  Common-Module/Test-Module/src/main/java/com/pawith/testmodule/RestDocsConfig.java
  build.gradle
  settings.gradle
Labels: ✅ Test, ⚙ Setting

#32 Pet 80 chore : RestDocs Index.html 생성 gradle task 추가
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .gitignore
  Api-Module/src/docs/asciidoc/Index.adoc
  Api-Module/src/main/resources/static/docs/Auth-API.html
  build.gradle
  settings.gradle
Labels: 🌏 Deploy&Infra, 📃 Docs, ⚙ Setting

#34 PET-80 chore : CI/CD 수정
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 🐞 BugFix, 🌏 Deploy&Infra

#35 PET-79 test : auth-application 테스트 코드 작성
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/common/consts/AuthConsts.java
  Auth-Module/auth-application/src/main/java/com/pawith/authmodule/application/port/out/command/OAuthInvoker.java
  Auth-Module/auth-application/src/test/java/com/pawith/auth/application/JWTExtractEmailServiceTest.java
  Auth-Module/auth-application/src/test/java/com/pawith/auth/application/JWTExtractTokenServiceTest.java
  Auth-Module/auth-application/src/test/java/com/pawith/auth/application/JWTVerifyServiceTest.java
  Auth-Module/auth-application/src/test/java/com/pawith/auth/application/OAuthServiceTest.java
Labels: ✅ Test
