Repository TEAM-SAMSION/Backend, pull requests merged in 2023-10, with the labels that each got.

#77 Pet 128 주차 달성률 비교 API 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoRateCompareResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoQueryService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Labels: ✨ Feature, ✅ Test

#78 Pet 131 refactor : Pamily 생성시 Pamily 프로필 이미지 같이 받도록 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamCreateUseCase.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: 🔨 Refactor

#79 Pet 130 feat : TodoTeam 코드를 통한 Pamily 조회 API 추가
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamSearchInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamRegisterUseCase.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoTeamQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#80 Pet 132 test : Todo-Application, Todo-Domain 테스트 코드 작성
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoRateGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/AssignSaveServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/CategoryQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoSaveServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/TodoTeamQueryServiceTest.java
Labels: ✅ Test

#81 Pet 133 refactor : Event Class 의존성 Common으로 수정
  .github/docs/Dependency.png
  Common-Module/src/main/java/com/pawith/commonmodule/event/UserSignUpEvent.java
  Domain-Module/Auth-Module/Auth-Application/build.gradle
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/OAuthInvoker.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/UserMapper.java
  Domain-Module/User-Module/User-Application/src/test/java/com/pawith/userapplication/handler/UserSignUpHandlerTest.java
Labels: 🔨 Refactor

#82 Pet 124 refactor : Category Id를 통해 Todo 반환 메소드 리팩터링
  .deploy/nginx/nginx.conf
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/AssignUserInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/UserRepository.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java
Labels: 🔨 Refactor

#83 Pet 124 refactor : 투두 리스트 조회 API 리팩터링
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterTermResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/CategoryRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/CategoryQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/CategoryQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#84 Pet 135 refactor : CategoryId를 통해 Assign 검색 쿼리 최적화
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
  README.md
Labels: 🔨 Refactor

#85 Pet 136 refactor : Google, Naver 소셜로그인 사용자 정보 요청 방식 feign client로 변경
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/GoogleOAuthFeignClient.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/NaverOAuthFeignClient.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/GoogleUserInfo.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/NaverUserInfo.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/AuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/GoogleOAuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/NaverOAuthHandler.java
Labels: 🔨 Refactor

#86 Pet 111 test : 소셜로그인 관련 테스트 코드 작성
  Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/LogoutUseCase.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/GoogleOAuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/LogoutUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/utils/TokenExtractUtils.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTExtractEmailUseCaseImplTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTExtractTokenUseCaseImplTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTVerifyServiceTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/LogoutUseCaseImplTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/OAuthUseCaseImplTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/OAuthInvokerTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/GoogleOAuthHandlerTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/NaverOAuthHandlerTest.java
  Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/OAuthController.java
Labels: ✅ Test

#87 Pet 137 feat : RefreshToken 재발급시 미사용 토큰 삭제 이벤트 메소드 추가
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/UnusedTokenExpireEventHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/request/UnusedTokenExpireEvent.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/OAuthInvoker.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/OAuthInvokerTest.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/TokenRepository.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/TokenDeleteService.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/TokenQueryService.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenDeleteServiceImpl.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenQueryServiceImpl.java
Labels: ✨ Feature

#88 Pet 126 feat : 토큰 재발급 API 추가
  Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/consts/AuthConsts.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/consts/IgnoredPathConsts.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/dto/TokenReissueResponse.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/ReissueUseCase.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/OAuthInvoker.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTExtractEmailUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTExtractTokenUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTVerifyUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/LogoutUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/OAuthUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/ReissueUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/LogoutUseCaseImplTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/OAuthInvokerTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/impl/ReissueUseCaseImplTest.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/TokenRepository.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/TokenDeleteService.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/impl/TokenDeleteServiceImpl.java
  Domain-Module/Auth-Module/Auth-Presentation/src/docs/asciidoc/Auth-API.adoc
  Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/OAuthController.java
  Domain-Module/Auth-Module/Auth-Presentation/src/test/java/com/pawith/authpresentation/OAuthControllerTest.java
Labels: ✨ Feature

#89 Pet 138 feat : 관리자 페이지 권한 수정 API 추가
  .deploy/Dockerfile
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/ManageRegisterInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/ManageRegisterListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/ChangeRegisterUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoTeamGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: ✨ Feature, ✅ Test

#90 Pet 140 feat : Todo 날짜, 이름 변경 API와 KakaoOAuthHandler, 권한 수정 API 리팩터링
  Common-Module/src/main/java/com/pawith/commonmodule/exception/Error.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/KakaoOAuthFeignClient.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/KakaoUserInfo.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/TokenInfo.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/handler/impl/KakaoOAuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/command/handler/impl/KakaoOAuthHandlerTest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/AuthorityChangeRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/ScheduledDateChangeRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/request/TodoDescriptionChangeRequest.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/exception/TodoException.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/exception/WrongScheduledDateException.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/ChangeRegisterUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoChangeUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/ChangeRegisterUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoChangeUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Todo.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#92 Pet 150 refactor : Register API URL 형식 변경
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
Labels: 🔨 Refactor

#91 Pet 142 fix : 토큰 검증시 ACCESS TOKEN, REFRESH TOKEN 검증하도록 조건 추가
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/JWTVerifyUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/JWTVerifyServiceTest.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/jwt/JWTProvider.java
  Domain-Module/Auth-Module/Auth-Domain/src/test/java/com/pawith/authdomain/jwt/JWTProviderTest.java
Labels: 🐞 BugFix

#93 Pet 151 refactor : Todo, Register, TodoTeam, Category API Url 수정
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: 🔨 Refactor

#94 Pet 153 feat : 포잇을 알게된 경로 저장 API 추가
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/dto/request/PathHistoryCreateRequest.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/PathHistoryMapper.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/UserMapper.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/service/PathHistoryCreateUseCase.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/PathHistory.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/repository/PathHistoryRepository.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/PathHistorySaveService.java
  Domain-Module/User-Module/User-Presentation/src/docs/asciidoc/User-API.adoc
  Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserController.java
  Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserControllerTest.java
Labels: ✨ Feature, ✅ Test

#95 Pet 155 refactor : DTO 네이밍 수정
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategoryInfoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/CategorySubTodoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterInfoListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/RegisterManageListResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoProgressRateCompareResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamInfoResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/dto/response/TodoTeamNameResponse.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/mapper/TodoTeamMapper.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/CategoryGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoRateGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoTeamGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/CategoryGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoRateGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/TodoTeamGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/CategoryController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/RegisterController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/main/java/com/pawith/todopresentation/TodoTeamController.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/CategoryControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/RegisterControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoControllerTest.java
  Domain-Module/Todo-Module/Todo-Presentation/src/test/java/com/pawith/todopresentation/TodoTeamControllerTest.java
Labels: 🔨 Refactor

#96 Pet 146 refactor : TodoTeam 탈퇴시 Register 삭제에서 탈퇴 필드 값 변경하는 방식으로 수정
  Common-Module/src/testFixtures/java/com/pawith/commonmodule/utils/FixtureMonkeyUtils.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/command/feign/response/KakaoUserInfo.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/RegistersGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoCreateUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/TodoGetUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/service/UnregisterUseCase.java
  Domain-Module/Todo-Module/Todo-Application/src/test/java/com/pawith/todoapplication/service/RegistersGetUseCaseTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Register.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterSaveService.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterQueryServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/service/RegisterSaveServiceTest.java
  Domain-Module/Todo-Module/Todo-Domain/src/test/java/com/pawith/tododomain/utils/RegisterTestFixtureEntityUtils.java
  Domain-Module/Todo-Module/Todo-Presentation/src/docs/asciidoc/Todo-API.adoc
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserQueryService.java
Labels: 🔨 Refactor

#98 Pet 143 feat : 사용자 탈퇴 API 추가
  .gitignore
  Common-Module/src/main/java/com/pawith/commonmodule/event/UserAccountDeleteEvent.java
  Domain-Module/Todo-Module/Todo-Application/src/main/java/com/pawith/todoapplication/handler/UserAccountDeleteOnTodoHandler.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/entity/Assign.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/AssignRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/RegisterRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/AssignDeleteService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterDeleteService.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/RegisterQueryService.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/service/UserDeleteUseCase.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserDeleteService.java
  Domain-Module/User-Module/User-Presentation/src/docs/asciidoc/User-API.adoc
  Domain-Module/User-Module/User-Presentation/src/main/java/com/pawith/userpresentation/UserController.java
  Domain-Module/User-Module/User-Presentation/src/test/java/com/pawith/userpresentation/UserControllerTest.java
Labels: ✨ Feature
