Repository TEAM-SAMSION/Backend, pull requests merged in 2024-02, with the labels that each got.

#206 Pet 302 feat : 소셜 로그인 성공 이벤트 처리 클래스 추가
  Common-Module/src/main/java/com/pawith/commonmodule/event/UserSignUpEvent.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/dto/OAuthRequest.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/OAuthSuccessHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/request/OAuthSuccessEvent.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/request/UnusedTokenExpireEvent.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/OAuthUseCase.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/impl/OAuthUseCaseImpl.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/OAuthInvoker.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/feign/GoogleOAuthFeignClient.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/feign/response/GoogleUserInfo.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/GoogleOAuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/handler/OAuthSuccessHandlerTest.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/service/OAuthUseCaseImplTest.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/entity/OAuth.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/exception/AuthError.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/exception/OAuthException.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/exception/OAuthNotFoundException.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/OAuthRepository.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/OAuthQueryService.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/OAuthSaveService.java
  Domain-Module/Auth-Module/Auth-Presentation/src/main/java/com/pawith/authpresentation/OAuthController.java
  Domain-Module/Auth-Module/Auth-Presentation/src/test/java/com/pawith/authpresentation/OAuthControllerTest.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/handler/UserSignUpHandler.java
  Domain-Module/User-Module/User-Application/src/main/java/com/pawith/userapplication/mapper/UserMapper.java
  Domain-Module/User-Module/User-Application/src/test/java/com/pawith/userapplication/handler/UserSignUpHandlerTest.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/UserAuthority.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/service/UserAuthoritySaveService.java
  Domain-Module/User-Module/User-Domain/src/test/java/com/pawith/userdomain/service/UserAuthoritySaveServiceTest.java
Labels: ✨ Feature, 🔨 Refactor

#207 Pet 303 chore : gradle 의존성 설정 자동화
  Api-Module/build.gradle
  Batch-Module/build.gradle
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/handler/OAuthSuccessHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/test/java/com/pawith/authapplication/handler/OAuthSuccessHandlerTest.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/repository/OAuthRepository.java
  Domain-Module/Auth-Module/Auth-Domain/src/main/java/com/pawith/authdomain/service/OAuthQueryService.java
  Domain-Module/User-Module/User-Domain/src/main/java/com/pawith/userdomain/entity/User.java
  gradle/customplugin/gradleutils.gradle
Labels: ⚙ Setting

#208 Pet 304 feat : 소셜 로그인 시 회원 정보 식별 id도 같이 받아오도록 추가
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/feign/response/TokenInfo.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/KakaoOAuthHandler.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/repository/TodoTeamQueryRepository.java
  Domain-Module/Todo-Module/Todo-Domain/src/main/java/com/pawith/tododomain/service/TodoTeamQueryService.java
  Domain-Module/Todo-Module/Todo-Infrastructure/src/main/java/com/pawith/todoinfrastructure/repository/TodoTeamRepositoryImpl.java
Labels: ✨ Feature, 🔨 Refactor

#209 Pet 306 refactor : 애플 로그인 jwt 라이브러리 변경
  Domain-Module/Auth-Module/Auth-Application/build.gradle
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java
Labels: 🔨 Refactor

#210 PET-306 refactor : OIDCToken 반환 형식 수정
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java
Labels: 🔨 Refactor

#211 PET-306 refactor : kid 값 추출 방식 변경, 그에 따른 OIDCToken 파싱 및 반환 형식 수정
  Domain-Module/Auth-Module/Auth-Application/src/main/java/com/pawith/authapplication/service/oauth/impl/AppleOAuthHandler.java
Labels: 🐞 BugFix, 🔨 Refactor
